2025-10-07 04:56:37,353 - task_manager - CRITICAL - C:\Users\pmokr\OneDrive\Рабочий стол\task-manager\src\app\exceptions\decorators.py:47 - Unexpected server error: send_notification_task() got an unexpected keyword argument 'recipient', traceback=<traceback object at 0x000001D4EA305EC0>
2025-10-07 04:56:37,353 - task_manager - CRITICAL - C:\Users\pmokr\OneDrive\Рабочий стол\task-manager\src\app\exceptions\decorators.py:47 - Unexpected server error: send_notification_task() got an unexpected keyword argument 'recipient', traceback=<traceback object at 0x000001D4EA305EC0>
2025-10-08 00:34:55,347 - task_manager - CRITICAL - C:\Users\pmokr\OneDrive\Рабочий стол\task-manager\src\app\exceptions\decorators.py:47 - Unexpected server error: AppBaseException.__init__() got an unexpected keyword argument 'detail', traceback=<traceback object at 0x000002EC4341A7C0>
2025-10-08 00:34:55,347 - task_manager - CRITICAL - C:\Users\pmokr\OneDrive\Рабочий стол\task-manager\src\app\exceptions\decorators.py:47 - Unexpected server error: AppBaseException.__init__() got an unexpected keyword argument 'detail', traceback=<traceback object at 0x000002EC4341A7C0>
